# Updating the publication lists

name: Update Publications

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *' # Runs at 10 am AEST

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      MANUSCRIPT_PATH: tex_files/cv # exclude the '.tex' / '.pdf' extension!
      LATEX: pdflatex

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ads
    - name: Install texlive
      run: |
        sudo apt-get update
        sudo apt-get install texlive-publishers \
                             texlive-latex-recommended \
                             texlive-latex-extra \
                             # texlive-fonts-recommended \
                             # texlive-fonts-extra
    - name: execute pub_maker.py
      env:
        ADS_TOKEN: ${{ secrets.ADS_TOKEN }}
      run: python code/get_pubs.py
    - name: execute write_tex.py
      run: python code/write_tex.py
    - name: check for changes
      run: |
        git config --local user.email "robot@jeffrey"
        git config --local user.name "Robot Jeffrey"
        git add -A
        git commit -m "Daily update of the publication list."
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
    - name: Build paper
      run: |
        cd ${MANUSCRIPT_PATH%/*}
        ${LATEX} ${MANUSCRIPT_PATH##*/}.tex
        ${LATEX} ${MANUSCRIPT_PATH##*/}.tex
    - name: Push paper
      run: |
        git checkout --orphan ${GITHUB_REF##*/}-pdf
        git rm -rf .github/
        cd ${MANUSCRIPT_PATH%/*}
        git rm -rf .
        git add -f ${MANUSCRIPT_PATH##*/}.pdf
        git -c user.name='Robot Jeffrey' -c user.email='robot@jeffrey' commit -m "Update the CV PDF"
        git push -q -f https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ${GITHUB_REF##*/}-pdf
